### ISSUE TITLE
Has a backdoor in it

### ISSUE THREAD

**Issue by Topher7lol** [Saumodunn/Brick-Hill#1]
Don't use it lol

**Comment by Saumodunn** [comment]
This does NOT have a backdoor in it, it was cloned straight from GitLab and uploaded onto GitHub.

Just because you are too incompetent to set this up does NOT mean it's a backdoor.

**Comment by Saumodunn** [comment]
To add further to my aforementioned comment, you can compare it to https://gitlab.com/Jefemy/site/-/tree/main

(Jefemy is the and was the developer of this source)

**Comment by Topher7lol** [comment]
You are calling me incompetent to set it up, nah, I don't even want it, ever heard of Spreelands? It is owned by my friend. He used this and it has a backdoor in it. Maybe try not to hack people or ruin sites before uploading stuff. Thx :)

**Comment by Topher7lol** [comment]
I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same. We saw that it has a backdoor in it and he had to restart the site.

**Comment by Topher7lol** [comment]
"It does NOT mean..." like jeez why you mad, pretty obvious it has a rat/backdoor in it lmfao

**Comment by whtepony** [comment]
> I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same. We saw that it has a backdoor in it and he had to restart the site.

This is a unmodified version of the OFFICIAL brick hill source, you've used BLDN or Brick Hill Clone which DOES have a backdoor you desperate skid.

https://brickimo.com - no backdoor.

**Comment by Topher7lol** [comment]
Did I say I was the owner of it lmao

**Comment by whtepony** [comment]
> Did I say I was the owner of it lmao

Then why try to set it up? Clearly there is no backdoor, you can check out https://brickimo.com, I set the site up in 4 minutes with no backdoors. ![Screenshot_20240407_180941_Samsung Internet.png](https://github.com/Saumodunn/Brick-Hill/assets/74684060/758aa50e-ac74-42a0-b8c5-26f6e0ba44be)

![Screenshot_20240407_180948_Samsung Internet.png](https://github.com/Saumodunn/Brick-Hill/assets/74684060/883a1d74-0e3b-4b06-a7ef-622f77beab80)

![Screenshot_20240407_180945_Samsung Internet.png](https://github.com/Saumodunn/Brick-Hill/assets/74684060/747aa365-f278-4d24-9943-1cf0d6d2b3f7)

![Screenshot_20240407_180955_Samsung Internet.png](https://github.com/Saumodunn/Brick-Hill/assets/74684060/58061e20-5b9d-41b6-b383-49b146487d5c)

![Screenshot_20240407_180951_Samsung Internet.png](https://github.com/Saumodunn/Brick-Hill/assets/74684060/80bb8a34-4175-4681-ab9b-37d93dee2904)

**Comment by Orio-nn** [comment]
> You are calling me incompetent to set it up, nah, I don't even want it, ever heard of Spreelands? It is owned by my friend. He used this and it has a backdoor in it. Maybe try not to hack people or ruin sites before uploading stuff. Thx :)

Let's not jump to conclusions. Why not screenshot what piece of code your friend believes is a backdoor and send it here so we can go from there. Otherwise this isn't really a battle either of you will win?

**Comment by Topher7lol** [comment]
Did I say I was attempting to set it up either lmao

**Comment by Topher7lol** [comment]
> > Did I say I was the owner of it lmao
> 
> Then why try to set it up? Clearly there is no backdoor, you can check out https://brickimo.com, I set the site up in 4 minutes with no backdoors. ![Screenshot_20240407_180941_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322974-758aa50e-ac74-42a0-b8c5-26f6e0ba44be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzQtNzU4YWE1MGUtYWM3NC00MmEwLWI4YzUtMjZmNmUwYmE0NGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMTQyMTFlYWVmOTMxMzEzOGU0NjdjZmQyN2Y1MDEyMzU1MDgwMjEzYmU3ZTExNjcwMjI5ZDMwZTM2NGQ0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zkj2AQ2C-RgVNZ7f_SlJlHHyy2Xaa8igOQ4nhvVb_4w)
> 
> ![Screenshot_20240407_180948_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322975-883a1d74-0e3b-4b06-a7ef-622f77beab80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzUtODgzYTFkNzQtMGUzYi00YjA2LWE3ZWYtNjIyZjc3YmVhYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZTQ2YjdlODQ2ZTcxYzZiYTlmMWE5OTdhNTQ1MGY1MzAzMGQ4ZWU3MGQyZWIwYzQyOGRkZTBlNzNhOWQ2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.104t845RUOwt_vwfwhAaqHODo1eJQeqWNVomDyrUFWA)
> 
> ![Screenshot_20240407_180945_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322976-747aa365-f278-4d24-9943-1cf0d6d2b3f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzYtNzQ3YWEzNjUtZjI3OC00ZDI0LTk5NDMtMWNmMGQ2ZDJiM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZDZkM2ZmODMwYTFhNzdjODg1ODM5MTJmNzA5NDU5MzMzYzJmZjY4ZDZkOTcyZjY3MDU3YTY3YTE4MTU0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0n4EVlmBjzbGLsn6A8ITVSubBQTanJ4XcxxC1vPWRo)
> 
> ![Screenshot_20240407_180955_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322977-58061e20-5b9d-41b6-b383-49b146487d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzctNTgwNjFlMjAtNWI5ZC00MWI2LWIzODMtNDliMTQ2NDg3ZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YzBjOTk0YTRkNDNiNTY3MWM4NzVhYTViZjRjM2Q2NmU0NDY4ZjZhMmNhZGYyNjBmNmM4ZDlkNTExZWM0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qv34KT4pMdqJo2rRH6bd7BwESJqHQscm6mMRLWtCrdc)
> 
> ![Screenshot_20240407_180951_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322978-80bb8a34-4175-4681-ab9b-37d93dee2904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzgtODBiYjhhMzQtNDE3NS00NjgxLWFiOWItMzdkOTNkZWUyOTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTkxNTZiNTEyYzdhYjFmMDhjMmFhZTNhODlmZTBmNmIyNTZmNDAzOTIyMzc3MWFkZTE5NGVmOWMzYjg3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SafiPAHUpJ55p9DMCRkUjEy_A32nf8hb5Yl69XR5zlQ)

Does bro think there's a door image in the site or something 💀

**Comment by whtepony** [comment]
What?

**Comment by whtepony** [comment]
> > > Did I say I was the owner of it lmao
> > 
> > Then why try to set it up? Clearly there is no backdoor, you can check out https://brickimo.com, I set the site up in 4 minutes with no backdoors. ![Screenshot_20240407_180941_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322974-758aa50e-ac74-42a0-b8c5-26f6e0ba44be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzQtNzU4YWE1MGUtYWM3NC00MmEwLWI4YzUtMjZmNmUwYmE0NGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMTQyMTFlYWVmOTMxMzEzOGU0NjdjZmQyN2Y1MDEyMzU1MDgwMjEzYmU3ZTExNjcwMjI5ZDMwZTM2NGQ0NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zkj2AQ2C-RgVNZ7f_SlJlHHyy2Xaa8igOQ4nhvVb_4w)
> > 
> > ![Screenshot_20240407_180948_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322975-883a1d74-0e3b-4b06-a7ef-622f77beab80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzUtODgzYTFkNzQtMGUzYi00YjA2LWE3ZWYtNjIyZjc3YmVhYjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZTQ2YjdlODQ2ZTcxYzZiYTlmMWE5OTdhNTQ1MGY1MzAzMGQ4ZWU3MGQyZWIwYzQyOGRkZTBlNzNhOWQ2MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.104t845RUOwt_vwfwhAaqHODo1eJQeqWNVomDyrUFWA)
> > 
> > ![Screenshot_20240407_180945_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322976-747aa365-f278-4d24-9943-1cf0d6d2b3f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzYtNzQ3YWEzNjUtZjI3OC00ZDI0LTk5NDMtMWNmMGQ2ZDJiM2Y3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkZDZkM2ZmODMwYTFhNzdjODg1ODM5MTJmNzA5NDU5MzMzYzJmZjY4ZDZkOTcyZjY3MDU3YTY3YTE4MTU0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X0n4EVlmBjzbGLsn6A8ITVSubBQTanJ4XcxxC1vPWRo)
> > 
> > ![Screenshot_20240407_180955_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322977-58061e20-5b9d-41b6-b383-49b146487d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzctNTgwNjFlMjAtNWI5ZC00MWI2LWIzODMtNDliMTQ2NDg3ZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YzBjOTk0YTRkNDNiNTY3MWM4NzVhYTViZjRjM2Q2NmU0NDY4ZjZhMmNhZGYyNjBmNmM4ZDlkNTExZWM0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qv34KT4pMdqJo2rRH6bd7BwESJqHQscm6mMRLWtCrdc)
> > 
> > ![Screenshot_20240407_180951_Samsung Internet.png](https://private-user-images.githubusercontent.com/74684060/320322978-80bb8a34-4175-4681-ab9b-37d93dee2904.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MzUzMTQsIm5iZiI6MTcxMjUzNTAxNCwicGF0aCI6Ii83NDY4NDA2MC8zMjAzMjI5NzgtODBiYjhhMzQtNDE3NS00NjgxLWFiOWItMzdkOTNkZWUyOTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDAwMTAxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NTkxNTZiNTEyYzdhYjFmMDhjMmFhZTNhODlmZTBmNmIyNTZmNDAzOTIyMzc3MWFkZTE5NGVmOWMzYjg3NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SafiPAHUpJ55p9DMCRkUjEy_A32nf8hb5Yl69XR5zlQ)
> 
> Does bro think there's a door image in the site or something 💀 

I had a stroke reading this.

**Comment by iceables** [comment]
you're talking about BLDN hill because that has a backdoor in it, salmon's open source bh doesnt have a backdoor, you got mistaken.

**Comment by Spreelands** [comment]
bruh topher is crazy cus hes not CEO anymore lol

Benklery(why im logged in the official account)

**Comment by iceables** [comment]
I'm the person who created Spreelands and I can confirm that I didn't use this source but instead used BLDN hill's source that had a backdoor, this does not have a backdoor and is trustable.

**Comment by iceables** [comment]
Also about the "I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same" all Laravel project folders are named almost the same, if you digged deeper and got comparison of both sources you'd realize that there are differences between the two.

**Comment by Spreelands** [comment]
hi iceables

**Comment by Topher7lol** [comment]
> Also about the "I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same" all Laravel project folders are named almost the same, if you digged deeper and got comparison of both sources you'd realize that there are differences between the two.

Tf are you here for just fucking ban me bro I'm waiting

**Comment by Spreelands** [comment]
> > Also about the "I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same" all Laravel project folders are named almost the same, if you digged deeper and got comparison of both sources you'd realize that there are differences between the two.
> 
> Tf are you here for just fucking ban me bro I'm waiting

Why you want to be banned so much? There's no reason to us ban you.

**Comment by iceables** [comment]
Fine i'll ban you if you want and i'll block you, don't come back saying sorry.

**Comment by Topher7lol** [comment]
No dont fine

**Comment by Topher7lol** [comment]
> > > Also about the "I was with someone else who owns spreelands trying to find the src to try find the backdoor and we found this, and looked at the Spreelands src which was the same" all Laravel project folders are named almost the same, if you digged deeper and got comparison of both sources you'd realize that there are differences between the two.
> > 
> > 
> > Tf are you here for just fucking ban me bro I'm waiting
> 
> Why you want to be banned so much? There's no reason to us ban you.

Because iceables hates me!

**Comment by Topher7lol** [comment]
> Fine i'll ban you if you want and i'll block you, don't come back saying sorry.

You just seem like your pissed off at me, and seem like u don't want me in spreelands, don't do it I'm just mad ok

**Comment by Saumodunn** [comment]
Closed

**Comment by Topher7lol** [comment]
> Fine i'll ban you if you want and i'll block you, don't come back saying sorry.

Bro please don't I'm just weird ok I take stuff personally I'm weird and I'm gonna kms just don't block me I was joking!

**Comment by Topher7lol** [comment]
> Fine i'll ban you if you want and i'll block you, don't come back saying sorry.

Please don't man ;-;

**Comment by whtepony** [comment]
BALL BALL BALLIN My granny called she say travy you work too hard I worry you forget about me

**Comment by Topher7lol** [comment]
> BALL BALL BALLIN My granny called she say travy you work too hard I worry you forget about me

The fuck is white pony here for now

**Comment by Orio-nn** [comment]
@Topher7lol @iceables @Spreelands You are all insanely schizophrenic

**Comment by Topher7lol** [comment]
Rude. Because I fucking am

**Comment by iceables** [comment]
of course

**Comment by EdwardDaPicker445** [comment]
What the hell went on

**Comment by Spreelands** [comment]
someone called it a backdoor

**Comment by Topher7lol** [comment]
shi cuh mb @Saumodunn can u like delete this issue 🙏 w man thx ill leave u alone. I honestly misunderstood cuz I just realised this is the legit src mb bro

**Comment by Topher7lol** [comment]
also mb @iceables cuz u never told me this was legit src (at the time)

**Comment by whtepony** [comment]
> someone called it a backdoor

There's no backdoor, if I get the time i'll upload a youtube video to https://youtube.com/@whtepony, on how to setup this source since it's relatively easy and takes no more than 5 minutes.

**Comment by Topher7lol** [comment]
> > someone called it a backdoor
> 
> There's no backdoor, if I get the time i'll upload a youtube video to https://youtube.com/@whtepony, on how to setup this source since it's relatively easy and takes no more than 5 minutes.

yes, apologies as i just now realise theres no backdoor, would it be okay if you could delete this issue?

**Comment by idkhowtoLOL** [comment]
> > > someone called it a backdoor
> > 
> > 
> > There's no backdoor, if I get the time i'll upload a youtube video to https://youtube.com/@whtepony, on how to setup this source since it's relatively easy and takes no more than 5 minutes.
> 
> yes, apologies as i just now realise theres no backdoor, would it be okay if you could delete this issue?

you know how to setup laravel ik how to set up laravel

**Comment by whtepony** [comment]
> [EdwardDaPicker445](/EdwardDaPicker445)

Who the fuck is [EdwardDaPicker445](https://github.com/EdwardDaPicker445)
